name: Android UI Test with Emulator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v2

      - name: Create AVD
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --force
          emulator -list-avds

      - name: Start emulator
        run: |
          nohup emulator -avd test -no-audio -no-window -no-boot-anim &
          adb wait-for-device
          adb shell getprop init.svc.bootanim
          bootanim=""
          until [[ "$bootanim" == *"stopped"* ]]; do
            bootanim=$(adb shell getprop init.svc.bootanim)
            echo "Waiting for emulator to start..."
            sleep 5
          done

      - name: Install dependencies
        run: ./gradlew build --stacktrace

      - name: Run Appium Tests
        run: ./gradlew connectedAndroidTest